name: Check Markdown links

on:
  # push:
  workflow_dispatch:
  # schedule:
  #    At 01:00 on Thursday
  #  - cron: "0 1 * * 4"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        # Quiet mode only shows errors in output not successful links too
        use-quiet-mode: 'yes'
        # Specify yes to show detailed HTTP status for checked links.
        use-verbose-mode: 'yes'
